### PR TITLE
p4est solver on a spherical mesh

### PR DESCRIPTION
**Pull request by amrueda**
This PR implements a version of the 2D p4est solver that runs on a spherical shell that is constructed from a cubed sphere. Since there are three Cartesian space dimensions on the surface of the sphere, we use the 2D p4est solver in combination with a 3D equation. 

The connectivities are inherited from the [p8est 3D cubed-sphere implementation](https://github.com/trixi-framework/Trixi.jl/pull/689), but they are adapted to p4est (2D). The discretization strategy follows the approach by:
* Giraldo (2001). A spectral element shallow water model on spherical geodesic grids. http://faculty.nps.edu/fxgirald/Homepage/Publications_files/Giraldo_IJNMF_2001.pdf.

The following visualization uses [this version](https://github.com/trixi-framework/Trixi2Vtk.jl/pull/82) of Trixi2Vtk:

https://github.com/amrueda/Trixi.jl/assets/29205060/a021fa8d-c070-492b-bacf-11f6dde5bdfb

### CODE REVIEW

**Comment by tristanmontoya** [comment]
I've added my covariant solver to this PR in https://github.com/trixi-framework/TrixiAtmo.jl/tree/tm/p4est_new_container

**Comment by tristanmontoya** [comment]
@amrueda I think we can merge this even if the dimension check isn't removed from the main Trixi.jl package yet, since my covariant solver will use it.

**Review by tristanmontoya — APPROVED** [review]
I'm going to merge this now; tests will be added for the Cartesian solver once [the dimension check in Trixi.jl is moved out of the inner constructor for SemidiscretizationHyperbolic](https://github.com/trixi-framework/Trixi.jl/pull/2039#issue-2467882558).

**Comment by ranocha** [comment]
> I'm going to merge this now; tests will be added for the Cartesian solver once [the dimension check in Trixi.jl is moved out of the inner constructor for SemidiscretizationHyperbolic](https://github.com/trixi-framework/Trixi.jl/pull/2039#issue-2467882558).

The new version of Trixi.jl including the fix is released

**Comment by tristanmontoya** [comment]
> > I'm going to merge this now; tests will be added for the Cartesian solver once [the dimension check in Trixi.jl is moved out of the inner constructor for SemidiscretizationHyperbolic](https://github.com/trixi-framework/Trixi.jl/pull/2039#issue-2467882558).
> 
> The new version of Trixi.jl including the fix is released

Great, thank you!

**Pull request merged**
